services:
  postgres:
      image: postgres:16
      container_name: leben-postgres
      environment:
        POSTGRES_USER: leben_user
        POSTGRES_PASSWORD: leben_pass
        POSTGRES_DB: leben_in_deutschland
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

  volumes:
    postgres_data: